version: '3.4'
name: diskloud
services:
  diskloud.server:
    container_name: diskloud.server
    image: ${DOCKER_REGISTRY-}diskloudserver
    build:
      context: .
      dockerfile: DisKloud.Server/Dockerfile
    depends_on:
      - diskloud_db
    ports:
      - ${HTTPS_PORT}:${HTTPS_PORT}
      - ${HTTP_PORT}:${HTTP_PORT}
    environment:
      - ConnectionStrings__Diskloud=Host=diskloud_db,${Bdd_port}; Database= DisKloud; Username = ${Bdd_User}; Password= ${Bdd_pwd};
      #- ASPNETCORE_HTTPS_PORTS=${HTTPS_PORT}
      - ASPNETCORE_HTTP_PORTS={HTTP_PORT} 
      - FilesPath=${FilesPath}
      - SercretKey=${SercretKey}
      - PASSWORD_ENV_SEEDED=some.long.password.fllkwefiwejf23049uwlekjf.sEFWEFGR98^&$
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${PASSWORD_ENV_SEEDED}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_ENVIRONMENT=Development



  diskloud_db:
     container_name: diskloud_db
     image: postgres
     environment:
        - POSTGRES_PASSWORD=${Bdd_pwd}
        - POSTGRES_USER=${Bdd_User}
        - POSTGRES_DB=DisKloud
        
     ports:
        - ${Bdd_port}:5432